stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps: 
    - src/get_data.py
    - src/load_data.py
    - source_code/Netflix_Movie.csv
    
    outs:
    - data/raw/Netflix_Movie.csv
    
  recommendation:
    cmd: python src/recomendation.py --config=params.yaml
    deps:
    - src/load_data.py
  
  
  # log_production_model:
  #   cmd: python src/log_production_model.py --config=params.yaml
  #   deps:
  #     - src/log_production_model.py