base: 
  project: NetFlix-Recomendation-System

data_source:
  s3_source: source_code/Netflix_Movie.csv

load_data:
  raw_dataset_csv: data/raw/Netflix_Movie.csv

recommendation:


reports:
  similarity_score: reports/similarity_score.json


# mlflow_config:
#   artifacts_dir: artifacts
#   experiment_name: Movie_Recommendation_System
#   run_name: mlops
#   registered_model_name: Movie_Recommendation_System_APP
#   remote_server_uri: http://127.0.0.1:5000/

